docs(apisix): wrote configure-routes
api7/docs pull request #21
Opened 2023-02-03 07:58 UTC by An-DJ

2023-02-04 14:00 UTC, juzhiyuan reviewed
先 Review 了这一部分

2023-02-06 01:22 UTC, An-DJ commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +See [Route](#) for a description of how to configure the more detailed rules (such as methods, host and so on) and rich plugins.
对我这里先预留了锚点，主要是这些 Concept 暂时还没有

2023-02-06 06:03 UTC, juzhiyuan commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +curl "http://127.0.0.1:9180/apisix/admin/routes/1" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
Use environment variable to disable API Key by default in quickstart shell.

2023-02-06 06:18 UTC, juzhiyuan commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +The Route with id `1` can be created by the command below. It matches all HTTP requests to `/anything/*` and forwards them to the Upstream of `httpbin`. The `X-API-KEY` is the authentication token of
anything -> http://httpbin.org/headers

2023-02-06 06:49 UTC, moonming requested changes

2023-02-06 06:49 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +The Route with id `1` can be created by the command below. It matches all HTTP requests to `/anything/*` and forwards them to the Upstream of `httpbin`. The `X-API-KEY` is the authentication token of
We can add a picture here to explain the example of this route

2023-02-06 06:49 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +The Route with id `1` can be created by the command below. It matches all HTTP requests to `/anything/*` and forwards them to the Upstream of `httpbin`. The `X-API-KEY` is the authentication token of
`1` is not a good name for route.

2023-02-06 06:49 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +We can validate the Route created by curl:
```suggestion
We can validate this route by curl:
```

2023-02-06 06:49 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +Besides, Upstream can be defined separately from Route. See [Admin API](#) for a description of how to manage the resources like Route and Upstream.
remove this first. you can add it back when admin API exists.

2023-02-06 06:49 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +We can validate the Route created by curl:
please change all `we` to `you`

2023-02-06 06:49 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +The **Admin API** provides resources management capabilities such as Route and Upstream. In this section, we use Admin API to create a Route for forwarding to the [httpbin](https://httpbin.org), whic
```suggestion
 In this section, you use API to create a route for forwarding to the [httpbin](https://httpbin.org), which provides testing facilities for HTTP requests and responses.
```

2023-02-06 06:54 UTC, moonming requested changes

2023-02-06 06:54 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +Apache APISIX provides flexible gateway management capabilities based on the concept of route. The simplest gateway model is the **Route-Upstream** model. **Route** and **Upstream** define the routin
```suggestion
Apache APISIX provides flexible gateway management capabilities based on the concept of the route. Route and upstream define the routing paths and targets of the requests and responses, respectively.
```

2023-02-06 06:54 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +* Use curl to echo a test request, showing how the APISIX proxies and forwards the API requests.
```suggestion
* Create a route connecting to an example upstream, which points to [httpbin](https://httpbin.org).
* Use curl to echo a test request, showing how the APISIX proxies and forwards the API requests.
```

2023-02-06 06:54 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +A **Route** is a routing path to the upstream targets. In Apache APISIX, Route matchs the client's request based on defined rules, loads and executes the corresponding plugins, and forwards the reque
```suggestion
A route is a routing path to the upstream targets. In Apache APISIX, the route matches the client's request based on defined rules, loads and executes the corresponding plugins, and forwards the request to the specified Upstream.
```

2023-02-06 07:08 UTC, moonming submitted a review, later dismissed

2023-02-06 07:08 UTC, moonming commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +If you haven’t completed the [Get APISIX](./#get-apisix) step already, complete that before proceeding.
I don't think we need `Prerequisites`

2023-02-07 03:50 UTC, juzhiyuan commented
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/2106987/217143697-2cfc3459-74b8-428e-8f86-27c9f5f2a8dc.png">

Let's use _Italic_ for new terms :)

2023-02-07 06:16 UTC, juzhiyuan approved these changes

2023-02-07 07:50 UTC, An-DJ commented
CC @juzhiyuan A caution has been added to remind the user.

![image](https://user-images.githubusercontent.com/24536972/217183391-32f5e08f-c305-43cc-80f9-cf09436265e0.png)

Besides, `[//]: <balabala>` maybe a useful tool to record the TODO item, such as the unsettled target link.

2023-02-07 08:50 UTC, An-DJ commented
CC @moonming

2023-02-07 09:14 UTC, juzhiyuan commented
Preview page: https://api7-docs-21.preview.api7.ai/apisix/getting-started/configure-routes

2023-02-07 10:30 UTC, shreemaan-abhishek requested changes

2023-02-07 10:30 UTC, shreemaan-abhishek commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +One Route should have _uri_ and the corresponding Upstream at least.
```suggestion
One Route should have a _URI_ and the corresponding Upstream at least.
```

2023-02-07 10:30 UTC, shreemaan-abhishek commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +Complete the [Get APISIX](./) step before proceeding.
I am not sure if `./` would work. Please confirm.

2023-02-07 10:30 UTC, shreemaan-abhishek commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +The authorization of API is switched off for a better experience in this tutorial. If you deploy the APISIX in the production environment, it's recommended to open it.
```suggestion
The authorization of API is switched off for a better experience in this tutorial. If you deploy the APISIX in the production environment, it's recommended to turn it on.
```

2023-02-07 10:47 UTC, juzhiyuan commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +One Route should have _uri_ and the corresponding Upstream at least.
Please keep `uri` as it's a parameter :)

2023-02-07 14:03 UTC, juzhiyuan commented on apisix_versioned_docs/version-3.1.0/getting-started/configure-routes.md
> +Complete the [Get APISIX](./) step before proceeding.
Yes, it works.

2023-02-07 14:03 UTC, merged